### ISSUE TITLE
Demo app

### ISSUE THREAD

**Issue by bajki** [MrBin99/LaravelEchoAndroid#10]
Can you upload working demo app?

Thanks,
Ivan

**Comment by dvlpr91** [comment]
Does this work?

**Comment by MrBin99** [comment]
Hello.

I'm not planning to do a demo app because doing this will require a Laravel application and a Laravel Echo Server up and running online just. Websockets are always tricky stuff and I don't want to maintain a such stack just for demo.

I hope you understand.

Bests,
