### ISSUE TITLE
Problem Implementation 

### ISSUE THREAD

**Issue by rayan-appzod** [MrBin99/LaravelEchoAndroid#13]
Hello 
i can't implemented this dependency libraray in my project ,

**Comment by MrBin99** [comment]
Hello,

Can you be more precise ? Which type of error do you get ?

**Comment by rayan-appzod** [comment]
![Capture](https://user-images.githubusercontent.com/50503125/65769469-46957c80-e13c-11e9-925d-2b1b94705637.PNG)
this is error i have got

**Comment by MrBin99** [comment]
Yeah the 1.0.0 does not exists.
Try this `implementation 'com.github.MrBin99:LaravelEchoAndroid:1.0.2'`
