### ISSUE TITLE
Trouble with reconnection.

### ISSUE THREAD

**Issue by dinalt2006** [MrBin99/LaravelEchoAndroid#14]
Does exist any opportunity to client automatic reconnection after echo disconnected from server?

**Comment by MrBin99** [comment]
Hello.
SocketIO will try to reconnect (a number defined of time) after any error but if it can't, it will throw an event.
You can listen to low level SocketIO events [(https://stackoverflow.com/questions/24224287/list-of-socket-io-events)](https://stackoverflow.com/questions/24224287/list-of-socket-io-events) using `echo.on`.
You can listen to those events and perform your connection code inside.

Hope that will help you.

**Comment by dinalt2006** [comment]
Many thanks, you are completely right! Your answer help me.
