### ISSUE TITLE
Duplication of code

### ISSUE THREAD

**Issue by zahid--ali** [MrBin99/LaravelEchoAndroid#2]
In the file [SocketIOChannel.java](https://github.com/MrBin99/LaravelEchoAndroid/blob/master/laravelechoandroid/src/main/java/net/mrbin99/laravelechoandroid/channel/SocketIOChannel.java) in the constructor your are subscribing twice to the channel. Please update this.

**Comment by MrBin99** [comment]
Oops, sorry.
I'll fix that now.
