### ISSUE TITLE
Crashed after leaving or disconect.

### ISSUE THREAD

**Issue by MJsaycon** [MrBin99/LaravelEchoAndroid#5]
I'm new to android so it's not clear for me what's wrong after using the library, I already setup the laravel echo and after leaving the private channel it gives me an error, for socket connection it was a successful connection I can received the data but I can't leave or disconect the laravel echo it gives me this error? How can I resolve this? whats missing? this is my logs after the crashed.

Logs:
09-10 17:58:14.777 11599-11599/tech.synq.SynQ E/Conversation ID: 86a675a5-1ee8-4ddf-a0a9-7672c290c2f3
09-10 17:58:14.777 11599-11599/tech.synq.SynQ E/Channel Type: null
09-10 17:58:14.781 11599-11599/tech.synq.SynQ D/AndroidRuntime: Shutting down VM
09-10 17:58:14.783 11599-11599/tech.synq.SynQ E/AndroidRuntime: FATAL EXCEPTION: main
    Process: tech.synq.SynQ, PID: 11599
    java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
        at java.util.HashMap$KeyIterator.next(HashMap.java:885)
        at net.mrbin99.laravelechoandroid.channel.SocketIOChannel.unbind(SocketIOChannel.java:188)
        at net.mrbin99.laravelechoandroid.channel.SocketIOChannel.unsubscribe(SocketIOChannel.java:102)
        at net.mrbin99.laravelechoandroid.connector.SocketIOConnector.leave(SocketIOConnector.java:135)
        at net.mrbin99.laravelechoandroid.Echo.leave(Echo.java:116)
        at tech.synq.SynQ.activities.MainActivity.updateConversationMessages(MainActivity.java:2830)
        at tech.synq.SynQ.adapters.DrawerLeftAdapter$9$1.run(DrawerLeftAdapter.java:219)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

**Comment by MrBin99** [comment]
I think you are trying to disconnect twice at the same time, maybe in different threads.
I will watch on my side if there is any problem on the library.

**Comment by MJsaycon** [comment]
I edited the library for the unbind into this:

```
    public void unbind() {
    for (String event : eventsCallbacks.keySet()) {
            socket.off(event);
            //eventsCallbacks.remove(event);
        }
        eventsCallbacks.clear();
    }
```

What I did was to clear all the events because I need to connect in a new private channel,
but I Think the problem is in this part of the code, I believe it needs to be updated in to an iterator
and check it with hasnext() if there are more items before it will remove the items.

**Comment by MJsaycon** [comment]
actually what I did was wrong I got the same error after creating a privatechannel and a presence channel, after using the leave method it gives me the java.util.ConcurrentModificationException error because I was removing the items in the map.

**Comment by MJsaycon** [comment]
So far this are the changes that I made

`
  @Override
    public void leave(String channel) {
        String privateChannel = "private-" + channel;
        String presenceChannel = "presence-" + channel;
        
        Object[] subscribe = channels.keySet().toArray();
        
        for (Object subscribes : subscribe){
            if (subscribes.equals(channel) || subscribes.equals(privateChannel) || subscribes.equals(presenceChannel)) {
                try {
                    channels.get(subscribes.toString()).unsubscribe(null);
                } catch (EchoException e) {
                    e.printStackTrace();
                }
                channels.remove(subscribes.toString());
            }
        }
        
    }

`


`
 public void unbind() {

        Iterator<String> it = eventsCallbacks.keySet().iterator();

        while (it.hasNext())
        {
            socket.off(it.toString());
            it.next();
            it.remove();
        }
        
    }

`

**Comment by MrBin99** [comment]
Does changes you made in the last comment fixed the crash ?
If so, I will update the lib with your code.

**Comment by MJsaycon** [comment]
yes it fix the crash please check if there are no mistake. Thank you for the response.

**Comment by MrBin99** [comment]
I don't get the changes you made in the leave method.
I understand for the unbind method but not for the other.

I think you made a mistake, no ?

```java
Iterator<String> iterator = eventsCallbacks.keySet().iterator();

while (iterator.hasNext()) {
    socket.off(iterator.next());
    iterator.remove();
}
```

Perhaps I cannot reproduce your crash in my sample application.

**Comment by zeeshansardar61** [comment]
![screen shot 2018-10-20 at 1 59 04 am](https://user-images.githubusercontent.com/18070844/47244130-d5b6f200-d40d-11e8-9c98-1a031602b04b.png)

I did everything, As u mentioned in documentation, I subscribed a public channel and its event, but onDestroy app crashes again and again. I m not using Socket anywhere other than this class. I am using the '1.0.1' of the library, is it the latest version on the lib?

**Comment by MrBin99** [comment]
Hello,
I was waiting for @MJsaycon to reply at my previous comment before pushing the fix he gave me because as I said, I cannot reproduce the crash. So I can't test if this fix actually fixes the problem.

I will push a version 1.0.2 of the lib. Please update it on your side and tell me if it fix the problem.

**Comment by zeeshansardar61** [comment]
How to Edit the library files, please let me know

**Comment by MrBin99** [comment]
In your `build.gradle` just replace the line you added following the documentation :
```gradle
dependencies {
    compile 'com.github.MrBin99:LaravelEchoAndroid:1.0.1'
}
```

Replace by :
```gradle
dependencies {
    compile 'com.github.MrBin99:LaravelEchoAndroid:1.0.2'
}
```
