### ISSUE TITLE
Presence channel issue

### ISSUE THREAD

**Issue by nowfalsalahudeen** [MrBin99/LaravelEchoAndroid#7]
presence channel joining and leaving not triggering
'here' returns only one user instead of all online users

**Comment by MrBin99** [comment]
Can you tell me more about your issue.
Are you sure this is not an issue with your Laravel application or Laravel Echo Server ?

**Comment by rannieo** [comment]
As per Laravel documentation [here](https://laravel.com/docs/5.7/broadcasting#presence-channels):

> All presence channels are also private channels; therefore, users must be authorized to access them. However, when defining authorization callbacks for presence channels, you will not return true if the user is authorized to join the channel. Instead, you should return an array of data about the user.

> The data returned by the authorization callback will be made available to the presence channel event listeners in your JavaScript application. If the user is not authorized to join the presence channel, you should return false or null:


Check you channels.
